# Generated by Django 4.1.5 on 2023-01-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_age', models.IntegerField()),
                ('emp_pnumber', models.IntegerField()),
            ],
        ),
    ]
